apify/apify-shared-js

- src/regexs.js
- test/regexs.js
A supplemental change that is needed for fixing https://github.com/apifytech/apify-js/issues/123
PR: https://github.com/apifytech/apify-js/pull/125
It also fixes Jira:AP-477
_It's a breaking change_
> Fix KVS regex to correctly filter path-unsafe characters

- package.json
- src/consts.js
Enables chunking of data pushed to datasets, see https://github.com/apifytech/apify-js/pull/138
> Add MAX_PAYLOAD_SIZE_BYTES = 9MB constant

- .eslintrc.json
- CHANGELOG.md
- package.json
- src/webhook_payload_template.js
- test/webhook_payload_template.js
Title says all. Putting it here since it's gonna be useful in SDK too when creating webhooks programmatically.
Currently does not support dot notation `{{var.prop}}`, but I'll add it later.
> Add WebhookPayloadTemplate class to handle curly braces webhook syntax

- CHANGELOG.md
- package.json
- src/webhook_payload_template.js
- test/webhook_payload_template.js
To support use of `resource.id` etc.
> Implement webhook template dot notation

- src/consts.js
Add a constant containing the coefficient for converting the run memory to available CPU cores of the run.
Necessary for [https://bitbucket.org/apifyteam/apify-system/pull-requests/1881](https://bitbucket.org/apifyteam/apify-system/pull-requests/1881).
> Add RUN_MEMORY_SIZE_TO_CPU_CORES_COEFF constant

- .babelrc
- package.json
On apify.com, we get `SyntaxError: Unexpected token '...'. Expected a property name ` on iOS 11 devices when calling  `defaultLog` from apify-shared/log.
Adding the `@babel/plugin-proposal-object-rest-spread` plugin should fix the issue.
https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread
> Babel plugin to compile object rest and spread to ES5

- src/markdown_renderers.js
- test/markdown_renderers.js
The title text was being generated with a lot of unwanted whitespace at the end. 
@vbartonicek says it's not urgent, so fixed for next package release
> Fix unwanted whitespace after title text

- CHANGELOG.md
- package.json
- src/marked.js
- test/marked.js
Improved custom code renderer to support default markdown fenced code block with explicitly specified language.
> Support for single language code tabs

- CHANGELOG.md
- package.json
- src/git.js
- test/git.js
I updated the function for converting relative paths to absolute paths in READMEs to fix issues with rendering some public actor READMEs.
Now it converts all relative URLs, like:
- `./path/to/image.jpg`
- `/root/relative/path/to/image.jpg`
- `relative/path/to/image.jpg`
It also makes sure not to convert Base64-encoded images.
> Update function to convert relative image paths in READMEs to absolute paths to support more URL formats

- CHANGELOG.md
- package.json
- src/markdown_renderers.js
- src/marked.js
- test/markdown_renderers.js
- test/marked.js
We're not using the current way to pass custom IDs to headings anywhere right now, because the markup in the required format renders badly if not using `apifyMarked`.
This PR reworks the way custom IDs are passed to this:
```md
````
becomes
````html
<h3 id="custom-id"><a href="#custom-id"></a>Heading text</h3>
````
The link is rendered empty, so it takes no space, but in Docs we're using it to render the "Copy to clipboard" link and icon, and we had to add it everywhere manually up until now.
The `apifyMarked` renderer is not used anywhere but in Docs, so this should not break anything, but I'm releasing this as a breaking change just in case.
> Rework custom heading renderer in apify-marked, update marked to fix vulnerability

- .gitignore
- package.json
This PR adds very basic automated typings to this module, as it is helpful (and needed) in order to complete the TS migration of https://github.com/apify/apify-storage-local-js (and any further modules).
It creates typings automatically on build by invoking the `tsc` compiler on the pre-babel-build JS and telling it to emit JUST declarations. I thought it'd be best if I inlined the options for now, as this makes for a simple setup that should be deploy-ready 😄 
*Note that yes, a LOT of the types are `any` due to lack of JSDocs, however they are enough for now*
CC: @pocesar @B4nan
> feat: add rudimentary typing support

- package.json
Turns out, the current CD deploy script deploys just the files in the `build` directory ( :c )
This PR makes the types be next to the files (and yes, it works, I tested locally!)
CC: @pocesar @B4nan @mnmkng
> chore: actually deploy these files

- packages/utilities/src/utilities.ts
Related: https://github.com/apify/apify-conductor/pull/103
> fix: make `configureLogger` accept `Log` instance instead of `Logger`

- packages/consts/src/consts.ts
At this point pre-pulling base `ACTOR_BASE_DOCKER_IMAGES`, takes cca 6 minutes in prod. This delays worker startup => platform scales slower under load.
This is an attempt to speed it up, by not pre-pulling deprecated images.
> feat: consts - skip prepulling deprecated images

- package.json
- packages/consts/package.json
- packages/datastructures/package.json
- packages/git/package.json
- packages/hubspot_client/package.json
- packages/image_proxy_client/package.json
- packages/input_schema/package.json
- packages/log/package.json
- packages/markdown/package.json
- packages/salesforce_client/package.json
- packages/utilities/package.json
Due to issues in frontend repos using webpack to build, we decided to remove
the ESM support for now.
Related: https://github.com/apify/apify-web/pull/1169
> fix: remove ESM support

- packages/markdown/package-lock.json
- packages/markdown/package.json
- packages/markdown/src/markdown_renderers.ts
Replacing the `git-url-parse` package in the markdown renderers with native Node URL parsing (it's not compatible with Safari).
> fix: replace git-url-parse with native method

- packages/hubspot_client/src/hubspot_client.ts
- test/hubspot_client.test.ts
Neede for syncing info from cognism to HubSpot - https://github.com/apify/apify-core/issues/3308
> feat: added methods for working with companies

- .gitignore
- package-lock.json
- package.json
- packages/input_schema/package.json
- packages/input_schema/src/input_schema.ts
- packages/input_schema/src/intl.ts
- test/input_schema.test.ts
- test/input_schema_definition.test.ts
- test/utilities.client.test.ts
BREAKING CHANGE: update ajv to v8 and set it as peerDependency
> feat: update input schema to use ajv v8

- packages/hubspot_client/src/hubspot_client.ts
- test/hubspot_client.test.ts
PR fixes error in syncing users to Hubspot. It happened when our primary email was not the primary email of the contact on HS side causing polluting our error logs.
Now we look up contact by both primary an additional emails.
> feat: look up hubspot contact by HS additional emails

- README.md
- packages/timeout/package.json
- packages/timeout/src/index.ts
- packages/timeout/tsconfig.build.json
- packages/timeout/tsconfig.json
- test/timeout.test.ts
Runs given handler and rejects with the given `errorMessage` (or Error instance) after given `timeoutMillis`, unless the original promise resolves or rejects earlier. Use `tryCancel()` function inside the handler after each await to finish its execution early when the timeout appears.
```ts
import { addTimeoutToPromise, tryCancel } from '@apify/timeout';
async function doSomething() {
await doSomethingTimeConsuming();
tryCancel();
await doSomethingElse();
tryCancel();
}
const res = await addTimeoutToPromise(
() => handler(),
200,
'Handler timed out after 200ms!',
);
```
This uses `AsyncLocalStorage` to hold the `AbortController` instances created inside the `addTimeoutToPromise` function. The context is shared for this package, and respects nesting of `addTimeoutToPromise` calls. This …
> feat: add `@apify/timeout` package with abortable promise timeout helper

- packages/timeout/src/index.ts
During testing it turns out that in some places the previous implementation
did not work correctly, probably due to some bugs in ALS. To get around those,
we now use the same way as before with a regular `setTimeout/clearTimeout` for
the timeout handler. We no longer have `cancelTimeout` abort controller instance,
as we clear the timeout instead of using abort signal.
> fix!: rewrite the `addTimeoutToPromise` helper

- packages/consts/src/regexs.ts
- test/regexs.test.ts
Solving LogDNA error bug, more info in Slack [here](https://apifier.slack.com/archives/G0134LE0JUB/p1638267910154500). 
In general:
Email with consecutive dots in it should not be allowed to register. It was tested by [Mailgun API](https://documentation.mailgun.com/en/latest/api-email-validation.html#request-examples) where those emails are marked as invalid.
The new regex was tested in MongoDB using the query below, now it returns 19 invalid emails, the same number as currently used regex:
`db.getCollection('users').find({
$and: [
{ 'emails.address': { $not: { $regex: /NEW_REGEX/  } } },
{ 'emails.address': { $ne: null } },
]
})`
Moreover, new `invalid email` was added to tests.
Any comments / reviews appreciated :-) 
Thanks!
> fix: consecutive dots in email are not allowed

- packages/utilities/src/utilities.ts
The interval ID now has its own type - `BetterIntervalID`, and we now have
better types for the `betterSetInterval` arguments, that no longer requires casting.
> fix: improve types for `betterSetInterval`

- packages/consts/src/consts.ts
This PR adds deprecated images which are still used on some actors - and it broke validation in some cases (there are 364 versions referencing one of those).
We'll get rid of those (and more) together with coming singlefile removal.
> feat(consts): added deprecated base images still used by some actors

- packages/markdown/src/marked.ts
- test/marked.test.ts
When writing "js / javascript" in md for docs, it always ended up with `Node.js` code tab instead of `Javasript`. Reported [here](https://apifier.slack.com/archives/C0L33UM7Z/p1642588984124400) .
cc @mnmkng
> fix(web): md to tab title for Javascript

- packages/consts/src/consts.ts
These constants were not used anywhere but in internal applications, so I moved them directly to the application code, where they belong.
> feat(consts): remove unused consts

- packages/hubspot_client/src/hubspot_client.ts
- test/hubspot_client.test.ts
This will be used by MP to sync data from kanban with deal in hubspot.
I didn't add any checks/transformation to data. As it is not clear now and it will most likely change. I would rather do the changes in app... Later when it settles I will add `updateDealFromMarketplaceProject` or something and delete `updateDeal`...
closes [apify-core/#5130](https://github.com/apify/apify-core/issues/5130)
> feat(hubspot_client): add updateDeal method

- package-lock.json
- package.json
- renovate.json
The new version seems not work properly yet, so skipping its update for now
> fix: ignore qrcode package in renovate

- packages/hubspot_client/src/hubspot_client.ts
- test/hubspot_client.test.ts
We want to set `Apify kanban link` property at HS contact to the link to the latest MP project.
> feat(hubspot_client): add support for kanban url to contact

- packages/markdown/src/markdown_renderers.ts
Lowercasing the hrefs breaks certain links, e.g. links containing actor IDs, so best to leave it up to the markdown author to control the capital letters of the links
> feat: remove lowercasing from markdown hrefs

- packages/consts/src/regexs.ts
For some reason my webstrom adds a `g` flag by default and I didn't noticed 😎
> fix(consts): remove g flag from regex

- packages/input_schema/src/schema.json
Allows adding schema URL to Input Schema, which will cause the majority of editors to download the schema automatically and enable autocomplete/validation.
```
"$schema": "https://raw.githubusercontent.com/apify/apify-shared-js/master/packages/input_schema/src/schema.json",
```
> feat: Allow $schema prop in Input schema

- test/regexs.test.ts
Adds test sugested here https://github.com/apify/apify-shared-js/pull/305#issuecomment-1145824773
> feat(consts): add test for 'g' flag in COMMA_SEPARATED_EMAILS_REGEX

- packages/input_schema/src/input_schema.ts
- test/input_schema.test.ts
This adds a better error message when a field of type `enum` has a wrong value.
Before:
`Field schema.properties.message.editor must be equal to one of the allowed values`
After:
`Field schema.properties.message.editor must be equal to one of the allowed values: "javascript", "python", "textfield", "textarea", "hidden"`
> feat(input_schema): better error message for wrong enum value

- packages/input_schema/src/schema.json
If you had duplicate items in an `enum` field definition in an input schema, the actor with such input schema would build successfuly, but then the input schema validation would not work. This fixes it.
Resolves #133.
> fix: enforce unique items in "enum" input schema properties

- package-lock.json
- packages/input_secrets/package.json
- packages/input_secrets/src/index.ts
- packages/input_secrets/src/input_secrets.ts
- packages/input_secrets/tsconfig.build.json
- packages/input_secrets/tsconfig.json
- packages/input_secrets/tsup.config.ts
- test/input_secrets.test.ts
Move the code from https://github.com/apify/apify-core/pull/8266
We need to use `decryptInputSecrets` and in the future `encryptInputSecrets` in apify-sdk, so I move it here.
> feat(input_secrets): add new package to encrypt and decrypt input secrets

- packages/markdown/src/marked.ts
Cannot import from `@apify/markdown` in project with `"type": "module"`. Minimal repo:
```
// package.json
{
"name": "module-test",
"main": "index.js",
"type": "module",
"scripts": {
"start": "node index.js"
},
"dependencies": {
"@apify/markdown": "^2.0.10"
}
}
```
```
// index.js
import { apifyMarked } from "@apify/markdown"
console.log(apifyMarked)
```
Run script: `npm run start`
Error:
```
file:///Users/nguyendan/work/module/node_modules/@apify/markdown/index.mjs:99
import { Renderer, lexer, parser } from "marked";
^^^^^
SyntaxError: Named export 'lexer' not found. The requested module 'marked' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'marked'; …
```
> fix(markdown): marked package named imports

- packages/consts/src/consts.ts
Increasing the max actor job log length to 10 MB, as we agreed recently.
> feat(consts): increase max length of actor job log to 10 MB

- packages/consts/src/consts.ts
- packages/utilities/src/utilities.ts
This PR bundles a few code cleanup changes #OCD: 
- Removed old `LEGACY_ACTOR_CATEGORIES` constant, `ALL_ACTOR_CATEGORIES` marked deprecated
- All legacy `ACT_XXX` constants marked as deprecated, added new `ACTOR_XXX` variants to be used instead
- Added data-for-generative-ai to `FORBIDDEN_USERNAMES_REGEXPS`
> chore: Deprecate old ACT_XXX constants in favor of new ACTOR_XXX ones

- packages/input_schema/src/schema.json
- test/input_schema.test.ts
Disallow empty enums in input schema, to make schemas like this invalid:
```jsonc
{
// ...
properties: {
myField: {
title: 'Field title',
type: 'string',
description: 'Some description',
enum: []
}
}
};```
> fix(input_schema): disallow empty `enum`s in input schema

- packages/utilities/src/webhook_payload_template.ts
- test/webhook_payload_template.test.ts
This PR
- makes parsing slightly more effective (one pass only)
- adds support for "interpolation" - using `{{var:resource.defaultDatasetId}}` syntax in strings - ie. adding the possibility to pass it to the input.
- It's intentionally slightly different mechanism than the parsing, as it does a different thing.
Theoretically it's breaking, I have an idea how to deal with it, just not sure if it's necessary.
> feat: allow using variables in fields of webhook payload template

- packages/log/src/logger.ts
Sadly, node: builtin modules import doesn't work with meteor js, where we need to use this package.
> fix: omits node: import from events builtin module

- packages/consts/src/regexs.ts
- packages/input_schema/src/intl.ts
- test/utilities.client.test.ts
Ondra needs to have custom proxy urls to allow https since he want's to test some provider proxies and they do not have http. He says it's working in crawlee, but our input schema does not allow it. I checked and it looks like this regex is only used for that one check.
> feat: allow custom proxies to be https

- packages/input_schema/src/schema.json
This adds the option for users to create multiselect input UI fields. We first need to merge this and then in apify-core update the input schema package in my second PR with the UI part and then update also worker to allow users to build actors with the new schema field.
The enum and enumTitles must be wrapped in items field sadly, instead of being directly on the property object, because that is the only way how json schema supports typing items of array.
> feat: added multiselect option to input schema

- packages/consts/src/consts.ts
- test/consts.test.ts
I added more actor env vars based on updated https://github.com/apify/actor-specs/#environment-variables
I added a test that checks if all actor env vars begin with `ACTOR_`.
I renamed `ENV_VARS` to `APIFY_ENV_VARS` and created a new `ENV_VARS` variable that just copies the values for backwards compatibility. Also added a test to check if this works correctly.
> feat: add more ACTOR_ env vars, add a test, rename ENV_VARS

- packages/consts/src/consts.ts
Increase max size of input schema.
> feat: bump imput schema max size to 200kB

- packages/input_secrets/src/input_secrets.ts
- packages/input_secrets/src/ow.ts
Needed for https://github.com/apify/apify-sdk-js/pull/233
> fix(input_secrets): fix ESM build

- packages/consts/src/consts.ts
This origin will be applied to runs started by the upcoming Actor Standby feature.
> feat(consts): add `STANDBY` meta origin

- packages/input_schema/src/intl.ts
- packages/log/src/logger_text.ts
- test/logger_text.test.ts
will be fixed proper once we build IIFE bundles via tsup
> fix(rollback): revert logging the `cause` property from errors

- packages/log/src/log.ts
- packages/log/src/log_consts.ts
- packages/log/src/log_helpers.ts
- packages/log/src/logger.ts
- packages/log/src/logger_json.ts
- packages/log/src/logger_text.ts
- packages/log/src/node_internals.ts
- packages/utilities/src/exponential_backoff.ts
- test/exponential_backoff.test.ts
- test/log.test.ts
- test/log_helpers.test.ts
- test/logger_text.test.ts
This is the proper reimplementation of https://github.com/apify/apify-shared-js/pull/428 & revert of https://github.com/apify/apify-shared-js/pull/434
```ts
import log from '@apify/log';
const err = new Error('Some error');
const errWithCause = new Error('Some error with cause', { cause: err });
const errWithNestedCause = new Error('Some error with nested cause', { cause: errWithCause });
log.exception(errWithNestedCause);
```
> feat: log error causes (without breaking things this time)

- packages/consts/src/regexs.ts
- test/regexs.test.ts
LinkedIn supports creating usernames with dashes and underscores so we should also allow it with our form validation
Reported in the [#bug channel](https://apify.slack.com/archives/C0L33UM7Z/p1719817208470629)
> fix(consts): updated linkedin profile regex to support underscore and dash in the username

- package-lock.json
- packages/pseudo_url/package.json
- packages/pseudo_url/src/pseudo_url.ts
- test/pseudo_url.test.ts
This replaces the only place where we used `@sapphire/shapeshift` with a custom validation.
> fix(pseudo_url): drop dependency on `@sapphire/shapeshift`

- packages/input_schema/src/schema.json
- packages/input_schema/src/types.ts
- test/input_schema.test.ts
This PR introduce new input schema `editor` values for `string` property:
`dataset`, `keyValueStore` and `requestQueue` based on issue: https://github.com/apify/apify-core/issues/12871
The editor will show storage inputs enabling users to search and select storage, then the storage id is taken as field value.
Input PR waiting for this: https://github.com/apify/apify-core/pull/17521
Docs PR: https://github.com/apify/apify-docs/pull/1211
> feat(input_schema): storage editor types

- packages/consts/src/consts.ts
This will need to bubble through to the Console and worker after it's merged to become effective.
> feat(consts): increase input schema max size to 500 kB

- packages/input_schema/src/input_schema.ts
- packages/input_schema/src/intl.ts
- packages/input_schema/src/schema.json
- packages/input_schema/src/types.ts
- packages/input_schema/src/utilities.ts
- test/input_schema_definition.test.ts
- test/utilities.client.test.ts
This PR introduce new input_schema properties `allowAbsolute` and `allowRelative` used when the `editor` property is set to `datepicker`:
- the `schema.json` is updated in the way, that properties `allowAbsolute` and `allowRelative` are valid only when `editor` is `datepicker`, `allowAbsolute` is considered as default and any of `allowAbsolute` or `allowRelative` is true
- value format validation
- unit tests for schema validation and value validation
- New datepicker with support for absolute and relative dates PR: https://github.com/apify/apify-core/pull/17465
- Docs PR: https://github.com/apify/apify-docs/pull/1227
> feat(input_schema): datepicker allowAbsolute/allowRelative properties and validation

- packages/consts/src/consts.ts
This PR deprecates default standby port along with changing its value to the conductor one. It also introduces a new env variable `ACTOR_STANDBY_URL` that will hold the URL of Actor standby for the given Actor run (if applicable)
There's also a possibility to deprecate `DEFAULT_CONTAINER_PORT` and create `DEFAULT_WEB_SERVER_PORT`, but I'm not sure if it's worth doing...
> feat(consts): deprecate default standby port, add standby URL

- packages/input_schema/src/schema.json
- test/input_schema_definition.test.ts
Solves: https://github.com/apify/apify-core/issues/15613
The issue was with `arrayProperty` because it enables additional properties (`"additionalProperties": true`) so not defined properties were accepted including `isSecret`.
This PR fixes `arrayProperty` ensuring that not defined properties are prohibited
Adding also missing test that check this
> fix(input_schema): disable isSecret for array properties

- packages/consts/src/consts.ts
- test/consts.test.ts
Affects https://github.com/apify/apify-core/issues/17545
Besides introduction of new Profile name restrictions, this also adjusts restrictions (regex) of valid username.
It does so to prevent users from inputing viable url addresses by removing a dot from allowed characters. By doing so, the username now cannot form a valid URL or Email domain.
See comment bellow for more info (@baldasseva mainly).
> feat(consts): introduce profile name (first, last, organization, ...) restrictions and adjust username regex

- packages/utilities/src/utilities.client.ts
- test/utilities.client.test.ts
Needed to solve https://github.com/apify/apify-core/issues/18466.
Now the `rel="noopener noreferrer nofollow" target="_blank"` is added only if url is outside from `apify.com` domain.
This enable passing hostname to `markedSetNofollowLinks` function and setting `rel="noopener noreferrer" target="_blank"` for apify domain but different hostname.
Once this is merged, next step would be to pass hostname from `safeMarkdown` in console/frontend down to `markedSetNofollowLinks`
> feat(utilities): markedSetNofollowLinks with hostname check

- packages/utilities/src/utilities.ts
- test/utilities.test.ts
Historically, functions scheduled with `betterSetInterval` needed to accept a callback and then call it when done, to schedule their next invocation. This was because Promises were not a thing in 2015 when this function was originally written. It's silly to have this requirement now, almost ten years later, when async/await and Promises are a normal feature.
This change adds support for scheduling any function, sync or async, accepting or not accepting a callback, and having it just work.
```js
betterSetInterval(async () => {
await myAsyncOperation();
}, 1000);
```
For backwards compatibility reasons, a dummy callback is still passed to the invoked function as its first argument, otherwise the functions that don't expect this change would break.
> feat: get `betterSetInterval` ready for 2025

- packages/consts/src/regexs.ts
- packages/input_schema/src/intl.ts
- test/regexs.test.ts
This PR adds support for SOCKS protocols into the `PROXY_URL_REGEX`. I also added unit tests for it while I was at it.
> feat: add support for SOCKS to PROXY_URL_REGEX

- packages/input_schema/src/schema.json
- packages/input_schema/src/types.ts
- test/input_schema.test.ts
We want to add file upload to the input schema, decided to go with url on the input.
Seems like a good idea to just use a special editor for this, instead of adding a new input type. The default fallback editor should work reasonably well everywhere.
- https://github.com/apify/apify-docs/pull/1524
> feat: fileUrl as string editor type

- packages/input_schema/src/schema.json
- packages/input_schema/src/types.ts
- test/input_schema.test.ts
As part of the [Actor permissions project](https://www.notion.so/apify/Public-Actor-permissions-design-document-1d1f39950a228015a679f276104123cb), we want to allow Actors to request access to resources via schema.
- The Actor input schema already supports annotating string fields with a `resourceType` to specify that the field should reference an Apify platform resource (practically, a storage, such as a dataset).
- This PR extends the input schema so that the Actor can not only specify that a certain string is actually a storage ID, but also what kind of access to the storage the Actor will require (read, or also write). For that reason, the PR adds a new property `resourcePermissions`.
- We will then use this information both to communicate this Actor requirement to the user, and to …
> feat(schema): add support for resource permissions

- packages/input_schema/src/schema.json
- test/input_schema.test.ts
Solves https://github.com/apify/apify-core/issues/20247
The `default` property should allow `default: null` if field has `nullable: true`
```
"test": {
"title": "test",
"description": "test",
"type": "integer",
"nullable": true, 
"default": null
}
```
Thanks to `unevaluatedProperties` from draft 2019 it's quite easy now
> feat(input_schema): Allow nullable field default to null

- packages/input_schema/src/input_schema.ts
- packages/json_schemas/schemas/actor.schema.json
- packages/json_schemas/schemas/dataset.schema.json
- packages/json_schemas/schemas/input.schema.json
- packages/json_schemas/schemas/key_value_store.schema.json
- packages/json_schemas/schemas/output.schema.json
- packages/json_schemas/src/actor.schema.ts
We have JSON schemas publicly available at `https://apify.com/schemas`:
- [`https://apify.com/schemas/v1/actor.json`](https://apify.com/schemas/v1/actor.json)
- [`https://apify.com/schemas/v1/input.json`](https://apify.com/schemas/v1/input.json)
- [`https://apify.com/schemas/v1/dataset.json`](https://apify.com/schemas/v1/dataset.json)
- [`https://apify.com/schemas/v1/key-value-store.json`](https://apify.com/schemas/v1/key-value-store.json)
- [`https://apify.com/schemas/v1/output.json`](https://apify.com/schemas/v1/output.json)
This sets the `$id` property to the respective URL.
Also add optional `$schema` property to all schemas so the actual schema can link the validation schema (our JSON schema) to provide validation lints in IDE.
> feat(json_schemas): Add $id property to JSON schemas

- packages/json_schemas/schemas/input.schema.json
- test/input_schema.test.ts
This PR allows the use of the `fileupload` input for an array of strings.
Instead of re-using the `arrayItemsStringlist` reference, I've added `arrayItemsFileupload` with the same shape.
It will work the same way as it currently works for a single string.
Related PR in console: https://github.com/apify/apify-core/pull/23289
The order of PRs does not matter: The UI will fallback to code input, and the input just won't do anything until it encounters the editor in schema.
> feat: add fileupload editor for string arrays
