package.json
src/log.js
test/log.js

Adds the ability to choose a log level and therefore increase or decrease the amount of logging.

Add log level to log; add tests

---

src/intl.js
src/utilities.client.js
test/utilities.client.js

Adds option to provide validation for proxy groups to proxy validation.

Input schema: Advanced proxy validation

---

src/intl.js
src/regexs.js
src/utilities.client.js
test/utilities.client.js

Also added option passed from application which controls whether user has any proxy groups available for automatic mode (now it does not validate this properly, because every user has access to residential and serp, but they are excluded from auto mode)

Input schema: Added custom proxy url validation

---

src/log.js

Removed log.methodCall and log.methodException functions, improved SOFT_FAIL/ERROR decision logic in log.exception() to be more aligned with error codes defined in app.
This must only be merged after https://bitbucket.org/apifyteam/apify-system/pull-requests/1895 !!!

Improvements in error logging

---

.babelrc
CHANGELOG.md
package.json
src/log.js
src/log_consts.js
src/log_helpers.js
src/logger.js
src/logger_json.js
src/logger_text.js
src/lru_cache.js
test/log.js
test/log_helpers.js
test/logger_json.js
test/utilities.client.js

I couldn't stand it so I finally make a color version of our logger. It's backward compatible except couple of changes in the main configuration (isProduction, logJson, ...) which will take just a few lines for each project. I think I will need to polish the code a bit but please check the API if you agree with it.
Here is the API: https://monosnap.com/file/YP7Z7kq8UdrwAiP0ahG4GzzlPKiThY
It's plugabble so it will fix this issue https://github.com/apifytech/apify-js/issues/409

Implementing new logger

---

package.json
src/intl.js
src/utilities.client.js
test/utilities.client.js

Adds validation for the selected country for Apify proxy.

Validate Apify proxy country

---

.eslintrc.json
package.json
src/health_checker.js
src/utilities.js
test/.eslintrc
test/health_checker.js
test/utilities.js

Adding health checker

---

CHANGELOG.md
package.json
src/markdown_renderers.js
src/marked.js
test/markdown_renderers.js
test/marked.js

This PR improves the functionality of custom code rendering for rendering code tabs in different languages.

Fix custom code rendering

---

package.json
src/utilities.client.js
src/utilities.js
test/utilities.js

Remove getPublicCrawlerNiceUrl and bluebird promises

---

src/markdown_renderers.js

https://apifier.slack.com/archives/CSKH5670R/p1607588764000100?thread_ts=1607576763.000100&cid=CSKH5670R

Change error to warning

---

.github/workflows/release.yml
CHANGELOG.md
package.json
src/markdown_renderers.js
src/regexs.js
src/utilities.js

Needed for: https://app.zenhub.com/workspaces/platform-team-5f6454160d9f82000fa6733f/issues/apify/apify-web/861

Add custom link and image rendering functions

---

packages/consts/src/consts.ts

Increased the length of actor name into 63 chars (DNS safe string length)

feat: Increased length of actor name

---

package-lock.json
package.json
packages/utilities/src/utilities.client.ts
test/utilities.client.test.ts

feat: added toString object property into escape property names for BSON

feat: added toString object property into escape property names for BSON

---

packages/markdown/src/markdown_renderers.ts
test/markdown_renderers.test.ts

I noticed that the tests could have nicer input data, so this is the update. No need for release, it's just for my own peace of mind :) 
also adding a test for image like generation with SSH URLs

chore: improve markdown tests and inputs

---

packages/utilities/src/utilities.ts

fix: add more forbidden usernames

---

packages/consts/src/consts.ts

Added `REAL_ESTATE`, `SPORTS`, and `EDUCATION` categories to the `ACTOR_CATEGORIES` const

feat: Added new actor store categories

---

package-lock.json
packages/log/src/log.ts

feat: allow `null` in additional log data

---

package-lock.json
package.json
packages/markdown/src/marked.ts

Added TypeScript, Rust, and GO

feat(markdown): add extra languages

---

packages/utilities/src/crypto.ts
test/crypto.test.ts

This way is recommended from node js docs for using key pair.

fix(utilities): use native node js class for public/private key pairs

---

packages/consts/src/consts.ts

Increasing the actor build timeout to 30 minutes.

feat: increased actor build timeout

---

packages/consts/src/regexs.ts
packages/utilities/src/utilities.ts
test/utilities.test.ts

chore(internal): Added APIFY_ID_REGEX to regexs, improved isForbiddenUsername()

---

.github/workflows/test_and_release.yaml

This changes the CI secrets to the ones from the organization.

chore: updated CI secrets

---

packages/consts/src/consts.ts

feat(consts): add `ACTOR_BUILD_ARGS` const

---

packages/input_schema/src/schema.json

For some reason AJV could not match the enum array property correctly, so instead I have made the array property conditional.

fix: Fixed broken array input definition

---

packages/consts/src/consts.ts

Increases build memory.
Merge only after https://github.com/apify/apify-core/pull/11070 is deployed.

feat: increase build memory size

---

packages/datastructures/src/lru_cache.ts
packages/log/src/logger_text.ts
packages/utilities/src/webhook_payload_template.ts
scripts/create-tsup-config.ts
test/logger_text.test.ts
tsconfig.build.json

Closes #427 
Doing it this way to make it as non-breaking as possible

chore: log cause when logging exceptions

---

packages/consts/src/consts.ts

Closes apify/apify-core#13926
Moving issues statuses to shared js.

feat: add issues statuses

---

package-lock.json
packages/dummy/CHANGELOG.md
packages/dummy/package.json
packages/dummy/src/index.ts
packages/dummy/tsconfig.build.json
packages/dummy/tsconfig.json
packages/dummy/tsup.config.ts

(and merging to master from CI)

feat: add dummy package to test PR toolkit ruleset

---

packages/input_schema/src/schema.json

related to https://github.com/apify/apify-core/issues/16271
I checked the tests and they seem to be quite generic, so it looks like this case should be covered too

feat: add prefill option to input schema

---

packages/consts/src/consts.ts
test/consts.test.ts

This PR introduces consts around env vars logic for Actor Standby.

feat(consts): add actor standby consts

---

packages/input_schema/src/utilities.ts
test/utilities.client.test.ts

Disables validation of datepicker input property based on: https://apify.slack.com/archives/C010Q0FBYG3/p1728907212870409

fix(input_schema): disable datepicker validation

---

packages/input_schema/src/types.ts

Add missing properties that are defined in schema.json to ts types

feat(input_schema): add missing ResourceArrayFieldDefinition properties to ts types
